swagger: "2.0"
info:
  title: Planets API
  description: API to control the planets data.
  version: 1.0.0
host: api.planets.com
schemes:
  - https
paths:
  /planets:
    get:
      summary: Returns a list of planets.
      description: This return only a list of planets that universe have without details.
      produces:
        - application/json
      responses:
        200:
          schema:
            $ref: '#/definitions/PlanetsSummaries'
          description: OK

definitions:
  SummariesHeader:
    type: object
    properties:
      numberOfElements:
        type: integer
      numberOfPages:
        type: integer
      page:
        type: integer
      pageSize:
        type: integer

  PlanetsSummaries:
    type: object
    properties:
      planetsSummaryHeader:
        type: object
        $ref: '#/definitions/SummariesHeader'
      planetsAbstracts:
        type: array
        items:
          $ref: '#/definitions/PlanetAbstract'

  PlanetAbstract:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string

  Planet:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      type:
        type: string
      resources:
        type: array
        items:
          $ref: '#/definitions/Resources'
      buildings:
        type: array
        items:
          $ref: '#/definitions/Building'

  Resources:
    type: object
    properties:
      id:
        type: integer
      type:
        type: string
      amount:
        type: integer

  Building:
    type: object
    properties:
      id:
        type: integer
      type:
        type: string
      cost:
        type: array
        items:
          $ref: '#/definitions/Resources'
      load:
        type: array
        items:
          $ref: '#/definitions/Resources'
